# Generated by Django 6.0.3 on 2026-09-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'receiver'], name='idx_chat_participants'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'is_read'], name='idx_chat_unread'),
        ),
        migrations.AddIndex(
            model_name='matchinteraction',
            index=models.Index(fields=['sender_pet'], name='idx_match_sender'),
        ),
    ]
